---
- name: Message of the day is managed
  hosts: web
  vars:
    motd_contact: ops@example.com
  tasks:
    - name: Message of the day is in place
      ansible.builtin.template:
        src: templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"
